insert into tblContent(content_seq,content,gisuBoard_seq) values (1,'너무 궁금해요~! 심심하신분 들어오세요! 다들 오늘 뭐하시나요??',3) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (2,'다들 취업은 어디로 하셨나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ 제발 도와주세요',85) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (3,'다들 오늘 뭐하시나요?? 인원 구해요~! 인원 구해요~!',45) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (4,'실무에서도 이렇게 하나요?? 심심하신분 들어오세요! 오류가 났는데 해결을 못하겠어요ㅠㅠ',82) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (5,'너무 궁금해요~! 다들 취업은 어디로 하셨나요?? 다들 취업은 어디로 하셨나요??',44) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (6,'심심하신분 들어오세요! 제발 도와주세요 심심하신분 들어오세요!',28) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (7,'다들 오늘 뭐하시나요?? 심심하신분 들어오세요! 제발 도와주세요',52) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (8,'다들 취업은 어디로 하셨나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ 제발 도와주세요',22) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (9,'다들 오늘 뭐하시나요?? 심심하신분 들어오세요! 다들 오늘 뭐하시나요??',87) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (10,'다들 오늘 뭐하시나요?? 다들 오늘 뭐하시나요?? 다들 오늘 뭐하시나요??',64) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (11,'너무 궁금해요~! 심심하신분 들어오세요! 다들 오늘 뭐하시나요??',77) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (12,'다들 오늘 뭐하시나요?? 심심하신분 들어오세요! 너무 궁금해요~!',71) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (13,'다들 취업은 어디로 하셨나요?? 심심하신분 들어오세요! 인원 구해요~!',4) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (14,'제발 도와주세요 너무 궁금해요~! 다들 취업은 어디로 하셨나요??',52) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (15,'실무에서도 이렇게 하나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ 오류가 났는데 해결을 못하겠어요ㅠㅠ',79) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (16,'너무 궁금해요~! 실무에서도 이렇게 하나요?? 심심하신분 들어오세요!',98) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (17,'너무 궁금해요~! 다들 오늘 뭐하시나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ',76) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (18,'오류가 났는데 해결을 못하겠어요ㅠㅠ 너무 궁금해요~! 오류가 났는데 해결을 못하겠어요ㅠㅠ',22) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (19,'오류가 났는데 해결을 못하겠어요ㅠㅠ 다들 취업은 어디로 하셨나요?? 인원 구해요~!',55) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (20,'오류가 났는데 해결을 못하겠어요ㅠㅠ 오류가 났는데 해결을 못하겠어요ㅠㅠ 심심하신분 들어오세요!',42) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (21,'심심하신분 들어오세요! 다들 취업은 어디로 하셨나요?? 심심하신분 들어오세요!',86) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (22,'제발 도와주세요 너무 궁금해요~! 인원 구해요~!',85) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (23,'심심하신분 들어오세요! 제발 도와주세요 실무에서도 이렇게 하나요??',96) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (24,'심심하신분 들어오세요! 심심하신분 들어오세요! 다들 취업은 어디로 하셨나요??',7) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (25,'다들 취업은 어디로 하셨나요?? 실무에서도 이렇게 하나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ',76) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (26,'오류가 났는데 해결을 못하겠어요ㅠㅠ 제발 도와주세요 오류가 났는데 해결을 못하겠어요ㅠㅠ',63) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (27,'다들 취업은 어디로 하셨나요?? 다들 취업은 어디로 하셨나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ',94) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (28,'제발 도와주세요 제발 도와주세요 실무에서도 이렇게 하나요??',86) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (29,'실무에서도 이렇게 하나요?? 너무 궁금해요~! 실무에서도 이렇게 하나요??',86) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (30,'인원 구해요~! 제발 도와주세요 다들 오늘 뭐하시나요??',63) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (31,'실무에서도 이렇게 하나요?? 심심하신분 들어오세요! 다들 취업은 어디로 하셨나요??',97) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (32,'다들 취업은 어디로 하셨나요?? 인원 구해요~! 실무에서도 이렇게 하나요??',70) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (33,'제발 도와주세요 다들 취업은 어디로 하셨나요?? 인원 구해요~!',37) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (34,'실무에서도 이렇게 하나요?? 인원 구해요~! 심심하신분 들어오세요!',35) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (35,'다들 취업은 어디로 하셨나요?? 다들 취업은 어디로 하셨나요?? 제발 도와주세요',77) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (36,'너무 궁금해요~! 인원 구해요~! 제발 도와주세요',97) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (37,'심심하신분 들어오세요! 너무 궁금해요~! 인원 구해요~!',20) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (38,'오류가 났는데 해결을 못하겠어요ㅠㅠ 다들 취업은 어디로 하셨나요?? 다들 취업은 어디로 하셨나요??',97) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (39,'심심하신분 들어오세요! 너무 궁금해요~! 너무 궁금해요~!',45) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (40,'실무에서도 이렇게 하나요?? 인원 구해요~! 다들 취업은 어디로 하셨나요??',63) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (41,'다들 오늘 뭐하시나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ 제발 도와주세요',74) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (42,'심심하신분 들어오세요! 다들 취업은 어디로 하셨나요?? 제발 도와주세요',1) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (43,'너무 궁금해요~! 심심하신분 들어오세요! 제발 도와주세요',51) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (44,'다들 오늘 뭐하시나요?? 실무에서도 이렇게 하나요?? 제발 도와주세요',92) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (45,'제발 도와주세요 너무 궁금해요~! 제발 도와주세요',93) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (46,'제발 도와주세요 제발 도와주세요 다들 취업은 어디로 하셨나요??',76) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (47,'인원 구해요~! 다들 오늘 뭐하시나요?? 제발 도와주세요',52) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (48,'오류가 났는데 해결을 못하겠어요ㅠㅠ 다들 오늘 뭐하시나요?? 심심하신분 들어오세요!',29) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (49,'실무에서도 이렇게 하나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ 인원 구해요~!',15) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (50,'다들 취업은 어디로 하셨나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ 인원 구해요~!',73) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (51,'너무 궁금해요~! 다들 오늘 뭐하시나요?? 너무 궁금해요~!',1) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (52,'실무에서도 이렇게 하나요?? 다들 취업은 어디로 하셨나요?? 다들 오늘 뭐하시나요??',75) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (53,'다들 오늘 뭐하시나요?? 다들 오늘 뭐하시나요?? 제발 도와주세요',23) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (54,'다들 오늘 뭐하시나요?? 제발 도와주세요 다들 오늘 뭐하시나요??',36) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (55,'실무에서도 이렇게 하나요?? 다들 취업은 어디로 하셨나요?? 다들 오늘 뭐하시나요??',47) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (56,'너무 궁금해요~! 너무 궁금해요~! 오류가 났는데 해결을 못하겠어요ㅠㅠ',49) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (57,'실무에서도 이렇게 하나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ 실무에서도 이렇게 하나요??',96) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (58,'심심하신분 들어오세요! 실무에서도 이렇게 하나요?? 다들 취업은 어디로 하셨나요??',37) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (59,'오류가 났는데 해결을 못하겠어요ㅠㅠ 오류가 났는데 해결을 못하겠어요ㅠㅠ 다들 취업은 어디로 하셨나요??',44) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (60,'인원 구해요~! 오류가 났는데 해결을 못하겠어요ㅠㅠ 다들 취업은 어디로 하셨나요??',9) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (61,'심심하신분 들어오세요! 다들 오늘 뭐하시나요?? 심심하신분 들어오세요!',24) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (62,'너무 궁금해요~! 인원 구해요~! 너무 궁금해요~!',84) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (63,'다들 취업은 어디로 하셨나요?? 실무에서도 이렇게 하나요?? 다들 취업은 어디로 하셨나요??',100) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (64,'실무에서도 이렇게 하나요?? 다들 취업은 어디로 하셨나요?? 인원 구해요~!',86) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (65,'다들 취업은 어디로 하셨나요?? 인원 구해요~! 다들 취업은 어디로 하셨나요??',38) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (66,'인원 구해요~! 오류가 났는데 해결을 못하겠어요ㅠㅠ 다들 오늘 뭐하시나요??',63) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (67,'다들 취업은 어디로 하셨나요?? 다들 취업은 어디로 하셨나요?? 다들 취업은 어디로 하셨나요??',33) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (68,'오류가 났는데 해결을 못하겠어요ㅠㅠ 다들 오늘 뭐하시나요?? 다들 오늘 뭐하시나요??',99) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (69,'실무에서도 이렇게 하나요?? 실무에서도 이렇게 하나요?? 다들 오늘 뭐하시나요??',11) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (70,'제발 도와주세요 인원 구해요~! 인원 구해요~!',97) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (71,'제발 도와주세요 인원 구해요~! 제발 도와주세요',1) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (72,'오류가 났는데 해결을 못하겠어요ㅠㅠ 심심하신분 들어오세요! 실무에서도 이렇게 하나요??',45) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (73,'제발 도와주세요 심심하신분 들어오세요! 다들 취업은 어디로 하셨나요??',87) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (74,'실무에서도 이렇게 하나요?? 제발 도와주세요 오류가 났는데 해결을 못하겠어요ㅠㅠ',4) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (75,'다들 오늘 뭐하시나요?? 실무에서도 이렇게 하나요?? 실무에서도 이렇게 하나요??',19) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (76,'오류가 났는데 해결을 못하겠어요ㅠㅠ 오류가 났는데 해결을 못하겠어요ㅠㅠ 실무에서도 이렇게 하나요??',72) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (77,'오류가 났는데 해결을 못하겠어요ㅠㅠ 실무에서도 이렇게 하나요?? 다들 오늘 뭐하시나요??',20) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (78,'제발 도와주세요 다들 취업은 어디로 하셨나요?? 다들 취업은 어디로 하셨나요??',58) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (79,'너무 궁금해요~! 너무 궁금해요~! 너무 궁금해요~!',41) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (80,'제발 도와주세요 제발 도와주세요 다들 오늘 뭐하시나요??',98) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (81,'인원 구해요~! 실무에서도 이렇게 하나요?? 인원 구해요~!',77) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (82,'제발 도와주세요 다들 취업은 어디로 하셨나요?? 실무에서도 이렇게 하나요??',47) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (83,'실무에서도 이렇게 하나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ 제발 도와주세요',41) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (84,'심심하신분 들어오세요! 실무에서도 이렇게 하나요?? 심심하신분 들어오세요!',22) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (85,'다들 취업은 어디로 하셨나요?? 실무에서도 이렇게 하나요?? 실무에서도 이렇게 하나요??',76) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (86,'인원 구해요~! 인원 구해요~! 너무 궁금해요~!',97) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (87,'너무 궁금해요~! 다들 취업은 어디로 하셨나요?? 다들 취업은 어디로 하셨나요??',40) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (88,'실무에서도 이렇게 하나요?? 다들 오늘 뭐하시나요?? 다들 취업은 어디로 하셨나요??',77) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (89,'너무 궁금해요~! 너무 궁금해요~! 실무에서도 이렇게 하나요??',35) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (90,'인원 구해요~! 너무 궁금해요~! 너무 궁금해요~!',5) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (91,'인원 구해요~! 실무에서도 이렇게 하나요?? 너무 궁금해요~!',25) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (92,'심심하신분 들어오세요! 심심하신분 들어오세요! 너무 궁금해요~!',98) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (93,'다들 취업은 어디로 하셨나요?? 인원 구해요~! 다들 오늘 뭐하시나요??',33) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (94,'제발 도와주세요 실무에서도 이렇게 하나요?? 다들 오늘 뭐하시나요??',31) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (95,'제발 도와주세요 인원 구해요~! 다들 오늘 뭐하시나요??',86) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (96,'실무에서도 이렇게 하나요?? 너무 궁금해요~! 인원 구해요~!',53) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (97,'제발 도와주세요 오류가 났는데 해결을 못하겠어요ㅠㅠ 너무 궁금해요~!',1) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (98,'심심하신분 들어오세요! 심심하신분 들어오세요! 인원 구해요~!',22) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (99,'심심하신분 들어오세요! 오류가 났는데 해결을 못하겠어요ㅠㅠ 제발 도와주세요',51) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (100,'너무 궁금해요~! 실무에서도 이렇게 하나요?? 실무에서도 이렇게 하나요??',63) ;
commit;