insert into tblContent(content_seq,content,gisuBoard_seq) values (1,'다들 취업은 어디로 하셨나요?? 실무에서도 이렇게 하나요?? 인원 구해요~!',100) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (2,'다들 오늘 뭐하시나요?? 심심하신분 들어오세요! 실무에서도 이렇게 하나요??',14) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (3,'제발 도와주세요 인원 구해요~! 오류가 났는데 해결을 못하겠어요ㅠㅠ',16) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (4,'심심하신분 들어오세요! 오류가 났는데 해결을 못하겠어요ㅠㅠ 너무 궁금해요~!',89) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (5,'제발 도와주세요 심심하신분 들어오세요! 다들 취업은 어디로 하셨나요??',30) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (6,'다들 오늘 뭐하시나요?? 다들 오늘 뭐하시나요?? 다들 오늘 뭐하시나요??',67) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (7,'인원 구해요~! 심심하신분 들어오세요! 제발 도와주세요',72) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (8,'실무에서도 이렇게 하나요?? 너무 궁금해요~! 다들 오늘 뭐하시나요??',98) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (9,'인원 구해요~! 제발 도와주세요 다들 오늘 뭐하시나요??',78) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (10,'실무에서도 이렇게 하나요?? 인원 구해요~! 심심하신분 들어오세요!',50) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (11,'다들 오늘 뭐하시나요?? 인원 구해요~! 실무에서도 이렇게 하나요??',72) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (12,'다들 오늘 뭐하시나요?? 제발 도와주세요 제발 도와주세요',76) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (13,'인원 구해요~! 인원 구해요~! 오류가 났는데 해결을 못하겠어요ㅠㅠ',38) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (14,'너무 궁금해요~! 제발 도와주세요 오류가 났는데 해결을 못하겠어요ㅠㅠ',21) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (15,'제발 도와주세요 제발 도와주세요 제발 도와주세요',99) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (16,'제발 도와주세요 오류가 났는데 해결을 못하겠어요ㅠㅠ 오류가 났는데 해결을 못하겠어요ㅠㅠ',57) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (17,'인원 구해요~! 실무에서도 이렇게 하나요?? 인원 구해요~!',40) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (18,'오류가 났는데 해결을 못하겠어요ㅠㅠ 너무 궁금해요~! 다들 취업은 어디로 하셨나요??',94) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (19,'오류가 났는데 해결을 못하겠어요ㅠㅠ 너무 궁금해요~! 실무에서도 이렇게 하나요??',35) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (20,'실무에서도 이렇게 하나요?? 다들 오늘 뭐하시나요?? 심심하신분 들어오세요!',5) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (21,'실무에서도 이렇게 하나요?? 다들 취업은 어디로 하셨나요?? 심심하신분 들어오세요!',62) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (22,'너무 궁금해요~! 심심하신분 들어오세요! 다들 오늘 뭐하시나요??',38) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (23,'오류가 났는데 해결을 못하겠어요ㅠㅠ 너무 궁금해요~! 너무 궁금해요~!',3) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (24,'다들 오늘 뭐하시나요?? 심심하신분 들어오세요! 실무에서도 이렇게 하나요??',77) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (25,'제발 도와주세요 제발 도와주세요 인원 구해요~!',20) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (26,'실무에서도 이렇게 하나요?? 실무에서도 이렇게 하나요?? 실무에서도 이렇게 하나요??',4) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (27,'다들 취업은 어디로 하셨나요?? 제발 도와주세요 오류가 났는데 해결을 못하겠어요ㅠㅠ',34) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (28,'인원 구해요~! 오류가 났는데 해결을 못하겠어요ㅠㅠ 다들 취업은 어디로 하셨나요??',81) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (29,'인원 구해요~! 인원 구해요~! 심심하신분 들어오세요!',55) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (30,'오류가 났는데 해결을 못하겠어요ㅠㅠ 심심하신분 들어오세요! 다들 오늘 뭐하시나요??',38) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (31,'너무 궁금해요~! 심심하신분 들어오세요! 오류가 났는데 해결을 못하겠어요ㅠㅠ',57) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (32,'너무 궁금해요~! 실무에서도 이렇게 하나요?? 심심하신분 들어오세요!',45) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (33,'인원 구해요~! 다들 취업은 어디로 하셨나요?? 제발 도와주세요',47) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (34,'제발 도와주세요 다들 오늘 뭐하시나요?? 다들 취업은 어디로 하셨나요??',40) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (35,'실무에서도 이렇게 하나요?? 다들 오늘 뭐하시나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ',16) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (36,'제발 도와주세요 실무에서도 이렇게 하나요?? 다들 오늘 뭐하시나요??',14) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (37,'너무 궁금해요~! 인원 구해요~! 오류가 났는데 해결을 못하겠어요ㅠㅠ',29) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (38,'다들 오늘 뭐하시나요?? 다들 취업은 어디로 하셨나요?? 너무 궁금해요~!',57) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (39,'오류가 났는데 해결을 못하겠어요ㅠㅠ 다들 오늘 뭐하시나요?? 다들 취업은 어디로 하셨나요??',97) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (40,'인원 구해요~! 인원 구해요~! 오류가 났는데 해결을 못하겠어요ㅠㅠ',78) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (41,'제발 도와주세요 제발 도와주세요 심심하신분 들어오세요!',24) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (42,'제발 도와주세요 다들 오늘 뭐하시나요?? 심심하신분 들어오세요!',72) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (43,'너무 궁금해요~! 제발 도와주세요 인원 구해요~!',58) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (44,'너무 궁금해요~! 제발 도와주세요 제발 도와주세요',86) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (45,'다들 취업은 어디로 하셨나요?? 다들 오늘 뭐하시나요?? 심심하신분 들어오세요!',43) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (46,'인원 구해요~! 다들 취업은 어디로 하셨나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ',67) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (47,'인원 구해요~! 심심하신분 들어오세요! 다들 오늘 뭐하시나요??',98) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (48,'다들 오늘 뭐하시나요?? 다들 오늘 뭐하시나요?? 실무에서도 이렇게 하나요??',54) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (49,'다들 취업은 어디로 하셨나요?? 실무에서도 이렇게 하나요?? 심심하신분 들어오세요!',60) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (50,'오류가 났는데 해결을 못하겠어요ㅠㅠ 제발 도와주세요 인원 구해요~!',34) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (51,'제발 도와주세요 인원 구해요~! 심심하신분 들어오세요!',96) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (52,'너무 궁금해요~! 다들 취업은 어디로 하셨나요?? 다들 취업은 어디로 하셨나요??',8) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (53,'실무에서도 이렇게 하나요?? 제발 도와주세요 심심하신분 들어오세요!',10) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (54,'다들 오늘 뭐하시나요?? 다들 취업은 어디로 하셨나요?? 너무 궁금해요~!',9) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (55,'다들 취업은 어디로 하셨나요?? 다들 취업은 어디로 하셨나요?? 다들 오늘 뭐하시나요??',86) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (56,'인원 구해요~! 다들 취업은 어디로 하셨나요?? 다들 취업은 어디로 하셨나요??',34) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (57,'다들 취업은 어디로 하셨나요?? 다들 오늘 뭐하시나요?? 너무 궁금해요~!',55) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (58,'다들 취업은 어디로 하셨나요?? 실무에서도 이렇게 하나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ',88) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (59,'너무 궁금해요~! 심심하신분 들어오세요! 오류가 났는데 해결을 못하겠어요ㅠㅠ',6) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (60,'너무 궁금해요~! 너무 궁금해요~! 제발 도와주세요',20) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (61,'심심하신분 들어오세요! 다들 취업은 어디로 하셨나요?? 다들 취업은 어디로 하셨나요??',1) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (62,'심심하신분 들어오세요! 다들 오늘 뭐하시나요?? 제발 도와주세요',22) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (63,'심심하신분 들어오세요! 오류가 났는데 해결을 못하겠어요ㅠㅠ 인원 구해요~!',66) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (64,'인원 구해요~! 심심하신분 들어오세요! 다들 오늘 뭐하시나요??',19) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (65,'다들 오늘 뭐하시나요?? 심심하신분 들어오세요! 다들 취업은 어디로 하셨나요??',84) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (66,'인원 구해요~! 너무 궁금해요~! 다들 오늘 뭐하시나요??',72) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (67,'인원 구해요~! 너무 궁금해요~! 다들 오늘 뭐하시나요??',87) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (68,'다들 취업은 어디로 하셨나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ 다들 오늘 뭐하시나요??',98) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (69,'제발 도와주세요 오류가 났는데 해결을 못하겠어요ㅠㅠ 제발 도와주세요',73) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (70,'실무에서도 이렇게 하나요?? 다들 취업은 어디로 하셨나요?? 실무에서도 이렇게 하나요??',82) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (71,'인원 구해요~! 너무 궁금해요~! 심심하신분 들어오세요!',9) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (72,'실무에서도 이렇게 하나요?? 실무에서도 이렇게 하나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ',88) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (73,'심심하신분 들어오세요! 오류가 났는데 해결을 못하겠어요ㅠㅠ 제발 도와주세요',76) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (74,'너무 궁금해요~! 제발 도와주세요 제발 도와주세요',97) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (75,'실무에서도 이렇게 하나요?? 다들 취업은 어디로 하셨나요?? 심심하신분 들어오세요!',7) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (76,'다들 취업은 어디로 하셨나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ 실무에서도 이렇게 하나요??',99) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (77,'다들 취업은 어디로 하셨나요?? 인원 구해요~! 다들 취업은 어디로 하셨나요??',2) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (78,'너무 궁금해요~! 다들 취업은 어디로 하셨나요?? 너무 궁금해요~!',37) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (79,'인원 구해요~! 제발 도와주세요 심심하신분 들어오세요!',17) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (80,'오류가 났는데 해결을 못하겠어요ㅠㅠ 다들 오늘 뭐하시나요?? 너무 궁금해요~!',73) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (81,'너무 궁금해요~! 실무에서도 이렇게 하나요?? 제발 도와주세요',47) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (82,'실무에서도 이렇게 하나요?? 심심하신분 들어오세요! 다들 취업은 어디로 하셨나요??',7) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (83,'너무 궁금해요~! 너무 궁금해요~! 실무에서도 이렇게 하나요??',8) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (84,'너무 궁금해요~! 다들 취업은 어디로 하셨나요?? 실무에서도 이렇게 하나요??',97) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (85,'오류가 났는데 해결을 못하겠어요ㅠㅠ 오류가 났는데 해결을 못하겠어요ㅠㅠ 다들 취업은 어디로 하셨나요??',24) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (86,'인원 구해요~! 오류가 났는데 해결을 못하겠어요ㅠㅠ 인원 구해요~!',51) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (87,'오류가 났는데 해결을 못하겠어요ㅠㅠ 심심하신분 들어오세요! 너무 궁금해요~!',95) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (88,'제발 도와주세요 오류가 났는데 해결을 못하겠어요ㅠㅠ 제발 도와주세요',14) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (89,'오류가 났는데 해결을 못하겠어요ㅠㅠ 심심하신분 들어오세요! 인원 구해요~!',88) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (90,'제발 도와주세요 오류가 났는데 해결을 못하겠어요ㅠㅠ 인원 구해요~!',74) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (91,'다들 오늘 뭐하시나요?? 실무에서도 이렇게 하나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ',36) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (92,'심심하신분 들어오세요! 실무에서도 이렇게 하나요?? 너무 궁금해요~!',38) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (93,'심심하신분 들어오세요! 다들 취업은 어디로 하셨나요?? 제발 도와주세요',58) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (94,'인원 구해요~! 제발 도와주세요 인원 구해요~!',84) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (95,'제발 도와주세요 심심하신분 들어오세요! 오류가 났는데 해결을 못하겠어요ㅠㅠ',6) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (96,'실무에서도 이렇게 하나요?? 너무 궁금해요~! 제발 도와주세요',55) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (97,'제발 도와주세요 다들 오늘 뭐하시나요?? 다들 취업은 어디로 하셨나요??',28) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (98,'제발 도와주세요 심심하신분 들어오세요! 너무 궁금해요~!',83) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (99,'다들 오늘 뭐하시나요?? 다들 오늘 뭐하시나요?? 오류가 났는데 해결을 못하겠어요ㅠㅠ',80) ;
insert into tblContent(content_seq,content,gisuBoard_seq) values (100,'제발 도와주세요 오류가 났는데 해결을 못하겠어요ㅠㅠ 실무에서도 이렇게 하나요??',61) ;
commit;