insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (1,'벌써 점심이네요..','2021-11-15',57) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (2,'이렇게 하시면 돼요!','2021-11-21',92) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (3,'내일은 뭐하면 좋을까요?','2021-06-16',96) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (4,'저는 여기 취업했어요!','2021-11-16',70) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (5,'이것도 궁금해요','2021-11-13',69) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (6,'이것도 궁금해요','2021-05-24',71) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (7,'벌써 점심이네요..','2021-04-20',97) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (8,'저는 여기 취업했어요!','2021-10-07',66) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (9,'이렇게 하시면 돼요!','2021-06-21',55) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (10,'이렇게 하시면 돼요!','2021-02-13',68) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (11,'내일은 뭐하면 좋을까요?','2021-11-26',15) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (12,'저도 잘 모르겠네요 ㅠㅠ','2021-01-28',91) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (13,'이 언어도 쓰실줄 아시나요??','2021-10-03',48) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (14,'이것도 궁금해요','2021-08-11',58) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (15,'벌써 점심이네요..','2021-12-19',16) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (16,'내일은 뭐하면 좋을까요?','2021-03-07',16) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (17,'내일은 뭐하면 좋을까요?','2021-11-09',40) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (18,'내일은 뭐하면 좋을까요?','2021-09-11',55) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (19,'저는 여기 취업했어요!','2021-03-15',7) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (20,'벌써 점심이네요..','2021-09-21',35) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (21,'저는 여기 취업했어요!','2021-06-05',86) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (22,'내일은 뭐하면 좋을까요?','2021-09-06',99) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (23,'이 언어도 쓰실줄 아시나요??','2021-01-19',10) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (24,'이렇게 하시면 돼요!','2021-03-01',76) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (25,'저는 여기 취업했어요!','2021-11-18',19) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (26,'벌써 점심이네요..','2021-02-16',90) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (27,'내일은 뭐하면 좋을까요?','2021-02-19',45) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (28,'이것도 궁금해요','2021-11-13',84) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (29,'벌써 점심이네요..','2021-07-16',22) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (30,'저도 잘 모르겠네요 ㅠㅠ','2021-02-10',52) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (31,'이 언어도 쓰실줄 아시나요??','2021-08-28',64) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (32,'저는 여기 취업했어요!','2021-11-09',10) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (33,'내일은 뭐하면 좋을까요?','2021-05-03',50) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (34,'이것도 궁금해요','2021-11-24',92) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (35,'이 언어도 쓰실줄 아시나요??','2021-01-22',48) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (36,'이렇게 하시면 돼요!','2021-07-17',48) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (37,'이 언어도 쓰실줄 아시나요??','2021-07-19',89) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (38,'저는 여기 취업했어요!','2021-09-23',71) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (39,'벌써 점심이네요..','2021-08-03',14) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (40,'내일은 뭐하면 좋을까요?','2021-11-19',86) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (41,'저는 여기 취업했어요!','2021-09-09',6) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (42,'저도 잘 모르겠네요 ㅠㅠ','2021-09-18',85) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (43,'이렇게 하시면 돼요!','2021-11-21',5) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (44,'이렇게 하시면 돼요!','2021-04-21',97) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (45,'내일은 뭐하면 좋을까요?','2021-09-14',35) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (46,'저도 잘 모르겠네요 ㅠㅠ','2021-07-16',99) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (47,'내일은 뭐하면 좋을까요?','2021-05-14',87) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (48,'내일은 뭐하면 좋을까요?','2021-11-10',9) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (49,'내일은 뭐하면 좋을까요?','2021-08-18',26) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (50,'이 언어도 쓰실줄 아시나요??','2021-05-20',73) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (51,'이렇게 하시면 돼요!','2021-05-03',100) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (52,'저도 잘 모르겠네요 ㅠㅠ','2021-04-21',98) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (53,'내일은 뭐하면 좋을까요?','2021-02-21',95) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (54,'이렇게 하시면 돼요!','2021-08-18',93) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (55,'내일은 뭐하면 좋을까요?','2021-08-19',76) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (56,'벌써 점심이네요..','2021-03-15',21) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (57,'이 언어도 쓰실줄 아시나요??','2021-09-09',47) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (58,'이렇게 하시면 돼요!','2021-05-28',12) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (59,'벌써 점심이네요..','2021-06-04',12) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (60,'벌써 점심이네요..','2021-09-20',72) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (61,'이것도 궁금해요','2021-12-17',14) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (62,'이것도 궁금해요','2021-08-17',51) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (63,'이것도 궁금해요','2021-09-18',25) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (64,'저도 잘 모르겠네요 ㅠㅠ','2021-11-18',16) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (65,'저는 여기 취업했어요!','2021-09-02',89) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (66,'이렇게 하시면 돼요!','2021-09-19',95) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (67,'이 언어도 쓰실줄 아시나요??','2021-06-25',86) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (68,'이 언어도 쓰실줄 아시나요??','2021-12-28',53) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (69,'저도 잘 모르겠네요 ㅠㅠ','2021-07-25',19) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (70,'저는 여기 취업했어요!','2021-11-05',10) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (71,'이 언어도 쓰실줄 아시나요??','2021-02-22',69) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (72,'저도 잘 모르겠네요 ㅠㅠ','2021-07-18',33) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (73,'저는 여기 취업했어요!','2021-07-26',95) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (74,'내일은 뭐하면 좋을까요?','2021-03-13',84) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (75,'벌써 점심이네요..','2021-06-09',14) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (76,'이 언어도 쓰실줄 아시나요??','2021-05-11',95) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (77,'이것도 궁금해요','2021-02-05',27) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (78,'이 언어도 쓰실줄 아시나요??','2021-09-10',7) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (79,'내일은 뭐하면 좋을까요?','2021-09-23',49) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (80,'내일은 뭐하면 좋을까요?','2021-03-21',68) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (81,'저는 여기 취업했어요!','2021-12-24',2) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (82,'이렇게 하시면 돼요!','2021-06-21',37) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (83,'내일은 뭐하면 좋을까요?','2021-10-28',95) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (84,'저도 잘 모르겠네요 ㅠㅠ','2021-05-17',12) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (85,'이 언어도 쓰실줄 아시나요??','2021-01-02',30) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (86,'저도 잘 모르겠네요 ㅠㅠ','2021-09-03',49) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (87,'내일은 뭐하면 좋을까요?','2021-06-05',89) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (88,'이렇게 하시면 돼요!','2021-06-09',65) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (89,'저는 여기 취업했어요!','2021-11-16',6) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (90,'이렇게 하시면 돼요!','2021-06-16',53) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (91,'이 언어도 쓰실줄 아시나요??','2021-04-22',54) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (92,'벌써 점심이네요..','2021-02-20',54) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (93,'이 언어도 쓰실줄 아시나요??','2021-04-07',52) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (94,'이것도 궁금해요','2021-01-05',60) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (95,'이 언어도 쓰실줄 아시나요??','2021-08-12',80) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (96,'저는 여기 취업했어요!','2021-06-03',57) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (97,'저는 여기 취업했어요!','2021-12-07',98) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (98,'벌써 점심이네요..','2021-10-22',4) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (99,'이렇게 하시면 돼요!','2021-06-24',35) ;
insert into tblCom_Comment(Com_Comment_seq,content,reg_time,con_comment_seq) values (100,'이렇게 하시면 돼요!','2021-12-02',100) ;
commit;