insert into tblStudentspec(student_seq , Education , certificate ) values (1, '박사', 'OCP,빅데이터 분석기사,빅데이터 분석기사,정보처리 기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (2, '전문대졸', '컴활') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (3, '전문대졸', 'SQLP,OCP,정보처리 산업기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (4, '고졸', '컴활') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (5, '고졸', '빅데이터 분석기사,OCP,정보처리 기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (6, '고졸', 'OCP,SQLP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (7, '대졸', 'SQLD,컴활') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (8, '중졸', '정보처리 산업기사,OCM') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (9, '박사', 'OCP,MOS,OCP,OCA') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (10, '박사', 'OCM,빅데이터 분석기사,OCA,SQLD') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (11, '고졸', '정보처리 산업기사,정보처리 기사,MOS,OCP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (12, '중졸', 'OCM') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (13, '중졸', 'SQLD,정보처리 기사,빅데이터 분석기사,정보처리 기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (14, '석사', 'MOS') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (15, '석사', 'SQLP,네트워크 관리사,빅데이터 분석기사,정보처리 기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (16, '석사', '빅데이터 분석기사,정보처리 기사,컴활') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (17, '석사', '네트워크 관리사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (18, '고졸', 'MOS') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (19, '석사', '정보처리 기사,OCM') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (20, '전문대졸', 'SQLP,컴활') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (21, '석사', '정보처리 산업기사,정보처리 기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (22, '박사', '컴활') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (23, '석사', 'OCM') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (24, '전문대졸', 'OCA') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (25, '전문대졸', 'SQLP,OCM,네트워크 관리사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (26, '대졸', '정보처리 기사,네트워크 관리사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (27, '중졸', '정보처리 산업기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (28, '고졸', '네트워크 관리사,빅데이터 분석기사,정보처리 산업기사,SQLD') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (29, '전문대졸', '컴활') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (30, '고졸', 'SQLD,OCA,OCA') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (31, '전문대졸', 'SQLP,네트워크 관리사,OCA,정보처리 산업기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (32, '석사', 'OCP,SQLD,OCA') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (33, '중졸', 'OCA,SQLD,MOS') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (34, '석사', 'MOS,SQLP,OCM') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (35, '대졸', 'MOS,OCM,정보처리 산업기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (36, '중졸', 'OCA,네트워크 관리사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (37, '전문대졸', 'MOS,컴활,네트워크 관리사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (38, '중졸', 'OCM') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (39, '전문대졸', 'MOS,SQLP,정보처리 산업기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (40, '석사', '정보처리 산업기사,OCP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (41, '대졸', 'OCM,컴활,OCA') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (42, '석사', '네트워크 관리사,OCP,OCM') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (43, '고졸', 'OCP,빅데이터 분석기사,정보처리 기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (44, '중졸', 'SQLP,네트워크 관리사,OCM,정보처리 기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (45, '대졸', 'SQLD') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (46, '석사', 'MOS') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (47, '박사', 'SQLP,컴활') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (48, '석사', 'SQLD,빅데이터 분석기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (49, '박사', 'OCM,빅데이터 분석기사,MOS') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (50, '대졸', '컴활,빅데이터 분석기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (51, '전문대졸', 'OCM') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (52, '전문대졸', '정보처리 기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (53, '박사', 'SQLP,OCA,정보처리 기사,OCM') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (54, '대졸', '네트워크 관리사,네트워크 관리사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (55, '석사', '네트워크 관리사,빅데이터 분석기사,정보처리 산업기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (56, '중졸', '네트워크 관리사,정보처리 기사,빅데이터 분석기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (57, '중졸', '컴활,MOS') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (58, '석사', '컴활') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (59, '고졸', '정보처리 산업기사,OCP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (60, '석사', '정보처리 기사,정보처리 산업기사,컴활') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (61, '전문대졸', '정보처리 기사,컴활,빅데이터 분석기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (62, '석사', '정보처리 산업기사,정보처리 기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (63, '고졸', 'MOS,SQLP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (64, '석사', 'OCA,네트워크 관리사,OCA,OCA') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (65, '중졸', 'OCP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (66, '중졸', '빅데이터 분석기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (67, '고졸', '빅데이터 분석기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (68, '전문대졸', '정보처리 산업기사,SQLD,OCA') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (69, '대졸', 'OCM') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (70, '중졸', 'OCA') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (71, '고졸', '정보처리 기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (72, '전문대졸', 'MOS,SQLD,컴활') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (73, '전문대졸', '컴활,MOS,OCP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (74, '석사', 'SQLD') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (75, '박사', 'OCP,SQLP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (76, '전문대졸', '컴활,OCM,네트워크 관리사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (77, '박사', '컴활,네트워크 관리사,MOS,빅데이터 분석기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (78, '석사', 'SQLD') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (79, '박사', 'OCM,MOS,빅데이터 분석기사,MOS') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (80, '중졸', '빅데이터 분석기사,SQLP,정보처리 기사,OCP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (81, '대졸', 'OCM,OCA') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (82, '중졸', 'OCP,OCP,SQLP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (83, '중졸', '컴활,MOS,빅데이터 분석기사,SQLP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (84, '석사', 'OCM') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (85, '중졸', 'MOS') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (86, '고졸', '정보처리 산업기사,빅데이터 분석기사,네트워크 관리사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (87, '대졸', '정보처리 산업기사,MOS') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (88, '전문대졸', '컴활,네트워크 관리사,OCP,OCP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (89, '전문대졸', 'OCM,컴활,컴활') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (90, '고졸', 'SQLD,컴활,OCM,빅데이터 분석기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (91, '석사', 'SQLD') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (92, '박사', 'MOS,SQLP,OCP,OCP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (93, '대졸', '빅데이터 분석기사,SQLP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (94, '전문대졸', 'OCA') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (95, '석사', 'SQLP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (96, '석사', '정보처리 기사,OCP') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (97, '박사', 'SQLD,OCM') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (98, '고졸', 'OCM,네트워크 관리사,빅데이터 분석기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (99, '고졸', 'OCM,SQLD,SQLD,빅데이터 분석기사') ;
insert into tblStudentspec(student_seq , Education , certificate ) values (100, '고졸', '컴활,네트워크 관리사,정보처리 기사,OCM') ;
commit;